try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(c){var g=function(b){var a=this,d={contID:"rotator",sliderClass:"slides",controlsClass:"controls",nextText:">>",prevText:"<<",z:1,transitionTime:1E3,gidAtt:"gid",timeoutTime:7500,showControls:!1,linkTo:!1,linkClickCallback:function(){},autoRotate:!1,appendControlsTo:!1},e;for(e in b)d[e]=b[e]||d[e];for(e in d)a[e]=d[e];a.container=null;a.slider=null;a.slides=null;a.controls=null;a.sliderTimeout=null;a.currentSlide=[];a.nextSlide=null;a.binaryControls=null;a.RUNNING=!1;a.other=!1;a.init=
function(){if(c("#"+a.contID).length)a.container=c("#"+a.contID),a.slider=a.container.find("."+a.sliderClass),a.slides=a.slider.children(),a.controls=a.makeControls(),a.controls.children().last().addClass("active"),a.slides.last().addClass("active"),a.currentSlide=a.slides.last(),a.slides.not(".active").fadeOut(0),c(window).resize(a.onResize),a.onResize(),a.RUNNING=!0;return a};a.isRunning=function(){return a.RUNNING};a.onResize=function(){if(a.container.is(":visible")){if(!a.sliderTimeout&&a.autoRotate)a.sliderTimeout=
setTimeout(a.sliderTimeoutFunc,a.timeoutTime)}else if(a.sliderTimeout&&a.autoRotate)clearTimeout(a.sliderTimeout),a.sliderTimeout=null};a.makeControls=function(){var b=c("<div />").addClass(a.controlsClass);a.slides.each(function(e){var d=c(this).attr(a.gidAtt);c("<div />",{text:e+1}).attr(a.gidAtt,d).click(a.ctrlClickHandle).appendTo(b)});(!a.showControls||a.showControls==="binary")&&b.hide();if(a.showControls==="binary")a.binaryControls=a.makeBinaryControls();a.appendControlsTo&&c(a.appendControlsTo).length?
b.appendTo(a.appendControlsTo):b.appendTo(a.container);return b};a.makeBinaryControls=function(){var b=c("<div />").addClass(a.controlsClass);c("<span />",{text:a.prevText}).addClass("prev").click(a.binaryCtrlClickHandle).appendTo(b);c("<span />",{text:a.nextText}).addClass("next").click(a.binaryCtrlClickHandle).appendTo(b);b.appendTo(a.container);return b};a.ctrlClickHandle=function(){var b=c(this).attr(a.gidAtt);a.slideChange(b);return a.linkClickCallback(b,a.linkTo)};a.binaryCtrlClickHandle=function(){var b=
c(this).hasClass("prev")?a.getPreviousSlide().attr(a.gidAtt):a.getNextSlide().attr(a.gidAtt);a.slideChange(b);return a.linkClickCallback(b,a.linkTo)};a.getNextSlide=function(){return a.currentSlide.next().length?a.currentSlide.next():a.currentSlide.parent().children().first()};a.getPreviousSlide=function(){return a.currentSlide.prev().length?a.currentSlide.prev():a.currentSlide.parent().children().last()};a.getSlideByID=function(){};a.slideChange=function(b){var e=a.getControlByID(b);if(!e.hasClass("active"))return a.sliderTimeout&&
clearTimeout(a.sliderTimeout),a.z++,a.nextSlide=a.getSlideByID(b),a.fadeChange(),a.controls.find(".active").removeClass("active"),e.addClass("active"),a.autoRotate?a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime):!0};a.fadeChange=function(){if(!a.nextSlide)return!1;a.slider.find(a.currentSlide).stop(!1,!1);a.slides.not(a.nextSlide).stop(!0,!1);a.nextSlide.addClass("active").css({zIndex:a.z}).stop(!0,!0).fadeTo(a.transitionTime,1);a.slides.not(a.nextSlide).stop(!0,!0).fadeOut(a.transitionTime).removeClass("active");
a.currentSlide=a.nextSlide;a.nextSlide=null};a.getControlByID=function(b){return!b?!1:a.controls.find("["+a.gidAtt+'="'+b+'"]')};a.getSlideByID=function(b){return!b?!1:a.slider.find("["+a.gidAtt+'="'+b+'"]')};a.sliderTimeoutFunc=function(){return a.slideChange(a.getNextSlide().attr(a.gidAtt))};return a.init()};window.EaseRotator=g;window.EaseRotatorController=function(b){var a=this,d={rotatorsConfig:[],timeoutTime:7500},e;for(e in b)d[e]=b[e]||d[e];for(e in d)a[e]=d[e];a.rotators={};a.sliderTimeout=
null;a.init=function(){if(typeof a.rotatorsConfig==="object"&&a.rotatorsConfig.length)c.each(a.rotatorsConfig,a.startRotator),a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime);return a};a.startRotator=function(){if(this.linkTo)this.linkClickCallback=a.linkClickCallback;a.rotators[this.contID]=new g(this)};a.sliderTimeoutFunc=function(){clearTimeout(a.sliderTimeout);c.each(a.rotators,a.rotateInstance);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)};a.rotateInstance=
function(){!this.autoRotate&&this.RUNNING&&this.container.is(":visible")&&this.slideChange(this.getNextSlide().attr(this.gidAtt));return!0};a.linkClickCallback=function(b,e){if(!b||!e)return!1;clearTimeout(a.sliderTimeout);var c=a.rotators[e];typeof c==="object"&&c.isRunning()&&c.slideChange(b);return a.sliderTimeout=setTimeout(a.sliderTimeoutFunc,a.timeoutTime)};return a.init()}})(jQuery);
(function(c){window.EasePhotoGallery=function(g){var b=this,a={galleryContCls:"ease-photo-gallery",linkCls:"ease-img-link",showTitles:!1,showDescriptions:!1,useFrame:!1,dataAttr:"ease_full",dataEl:!1,paginate:!1,paginateContCls:"gallery-page-controls",popupId:"easePopup"},d;for(d in g)a[d]=g[d]||a[d];for(d in a)b[d]=a[d];b.currentI=0;b.allData=[];b.fullData=[];b.currentPage=1;b.maxPages=0;b.pageContainer=!1;b.pageControls=!1;b.isIE=Ease.ie||c("html.ie").length?!0:!1;b.galleryExists=!1;b.popup=!1;
b.frameCont=null;b.frame=null;b.init=function(){if(c("."+b.galleryContCls).length){b.galleryExists=!0;b.gallery=c("."+b.galleryContCls);if(b.paginate&&b.dataEl)return b.initPaginated();b.links=b.gallery.find("."+b.linkCls);b.links.each(function(a){var f=c(this).attr(b.dataAttr);b.allData[a]=c.parseJSON(f)});b.links.click(b.linkClick);c("body").click(b.closePop)}};b.initPaginated=function(){for(var a=JSON.parse(c(b.dataEl).text()),f=0;f<a.length;f++)b.fullData.push(a[f]),b.allData.push(a[f].full);
b.maxPages=Math.ceil(a.length/b.paginate);b.useFrame&&b.makeFrame();b.makePageContainer();b.makePaginateControls();c.fn.disableSelection&&c(".pageNext, .pagePrev").disableSelection();b.buildPage();c("body").click(b.closePop)};b.makeFrame=function(){var a=b.fullData[0];b.frameCont=c("<div />",{id:"gallery-frame"});b.frame=c("<img />",{src:a.full.src,thisI:0,alt:a.full.title}).attr(b.dataAttr,JSON.stringify(a.full)).click(b.loadPhoto).appendTo(b.frameCont);b.frameTip=c("<div />",{html:"Click to expand"}).addClass("frame-tip").appendTo(b.frameCont);
return b.frameCont.insertBefore(b.gallery)};b.frameClick=function(){};b.makePageContainer=function(){b.pageContainer=c("<div />",{id:"gallery-page-container"});return b.pageContainer.prependTo(b.gallery)};b.buildPage=function(){var a=b.currentPage*b.paginate-b.paginate,c=b.currentPage*b.paginate-1;for(b.pageContainer.html("");a<=c;a++)a<b.fullData.length&&b.makeThumbLink(a).appendTo(b.pageContainer);b.pageControls.find(".pageCounter").text(""+b.currentPage+" of "+b.maxPages)};b.makeThumbLink=function(a){var f=
b.fullData[a];return c("<a>",{href:f.full.src,thisI:a,title:f.full.title,html:c("<img />",{src:f.thumb[0],width:f.thumb[1],height:f.thumb[2]})}).attr(b.dataAttr,JSON.stringify(f.full)).addClass(b.linkCls).click(b.linkClick)};b.makePaginateControls=function(){var a={nextBttn:c("<div />",{html:"Next Page"}).addClass("pageNext").click(b.nextPage),prevBttn:c("<div />",{html:"Prev Page"}).addClass("pagePrev").click(b.prevPage),counter:c("<div />").addClass("pageCounter"),clear:c("<div />").addClass("clearfix")};
b.pageControls=c("<div />",{}).addClass(b.paginateContCls);for(var f in a)b.pageControls.append(a[f]);return b.pageControls.insertAfter(b.pageContainer)};b.nextPage=function(){b.currentPage<b.maxPages?b.currentPage++:b.currentPage=1;b.buildPage()};b.prevPage=function(){b.currentPage>1?b.currentPage--:b.currentPage=b.maxPages;b.buildPage()};b.linkClick=function(a){a.stopPropagation();a.preventDefault();return b.useFrame?b.loadPhotoInFrame.call(this,a):b.loadPhoto.call(this,a)};b.loadPhotoInFrame=function(a){a.stopPropagation();
a.preventDefault();a=c(this).attr("thisI");b.frame.attr({thisI:c(this).attr("thisI"),src:b.fullData[a].full.src}).attr(b.dataAttr,JSON.stringify(b.fullData[a].full))};b.loadPhoto=function(a){a.stopPropagation();a.preventDefault();b.currentI=c(this).attr("thisI")?c(this).attr("thisI"):c(this).index();b.makePopup()};b.closePop=function(){b.popup&&b.popup.hide()};b.nextPop=function(){b.currentI++;if(b.currentI>=b.allData.length)b.currentI=0;b.switchPop()};b.prevPop=function(){b.currentI==0?b.currentI=
b.allData.length-1:b.currentI--;b.switchPop()};b.positionPop=function(){var a=b.popup.width();b.popup.height();dW=c(window).width();sT=c(document).scrollTop();left=Math.floor((dW-a)/2);left<0&&(left=0);b.popup.css({top:40+sT,left:left}).show()};b.resizeHeight=function(a,b,c){a=Math.round(c*b/a);return{height:c,width:a}};b.resizeWidth=function(a,b,c){return{height:Math.round(c*a/b),width:c}};b.switchPop=function(){b.popup.children("img, #pDesc, #pTitle").remove();var a=b.allData[b.currentI],d=c(window).height()-
80,j=c(window).width()-40,k=a.height,h=a.width;if(h>j)j=b.resizeWidth(k,h,j),k=j.height,h=j.width;if(k>d)j=b.resizeHeight(k,h,d),k=j.height,h=j.width;d={img:c("<img />",{src:a.src,height:k,width:h}).click(b.nextPop)};if(b.showTitles)d.title=c("<div />",{id:"pTitle",html:a.title});if(b.showDescriptions)d.desc=c("<div />",{id:"pDesc",html:a.desc});for(var g in d)b.popup.append(d[g]);b.positionPop()};b.makePopup=function(){if(!b.popup){var a={nextBttn:c("<div />",{id:"pNext",html:"next"}).click(b.nextPop),
prevBttn:c("<div />",{id:"pPrev",html:"prev"}).click(b.prevPop),closeBttn:c("<div />",{id:"pClose",html:"&times;"}).click(b.closePop)};b.popup=c("<div />",{id:b.popupId}).click(function(a){a.stopPropagation()});for(var d in a)b.popup.append(a[d]);b.popup.prependTo("body")}b.switchPop()};b.init();c(window).resize(function(){b.popup&&!b.popup.is(":hidden")&&b.switchPop()});return b.galleryExists?b:!1}})(jQuery);(function(c){function g(){if(!c("#sidebar").length)return!1;var a=c("#sidebar"),b=c("#content");c("#whole");var f=c("#whole").outerWidth(),j=c("body").position().top*-1;a.width();var g=parseInt(a.css("right").replace("px",""));parseInt(a.css("top").replace("px",""));var h,m,l=!1,n,o=function(){h=a.offset().left;m=b.offset().top+j;n=a.is(":hidden");l&&(h=b.offset().left+f+g,a.css({left:h}));c(window).trigger("scroll")};o();c(window).resize(o);c(window).scroll(function(){n||(c(this).scrollTop()>m?l||
(a.css({position:"fixed",left:h,right:"auto"}),l=!0):l&&(a.css({position:"absolute",right:g,left:"auto"}),l=!1))});c(window).trigger("scroll")}function b(){if(c("nav#access").length){var b=c("nav#access"),e=b.find("li");(function(){if(c(window).width()>=a){var f=0;e.each(function(){f+=c(this).outerWidth()});var g=Math.floor((b.width()-f)/(e.length-1)-5);e.not(":last").css({marginRight:g});e.last().css({marginRight:0})}})();e.each(function(){c(this).find("a").attr("href")===window.location.href&&c(this).addClass("current-menu-item current_page_item")})}}
var a=0;c(document).ready(function(){c("html.ie").length?Ease.ie=!0:Ease.ie=!1;c("html.lte8").length?Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;b();g();new EaseRotator({transitionTime:750,timeoutTime:7E3,showControls:!0,autoRotate:!0});new EasePhotoGallery({paginate:25,useFrame:!0,dataEl:"#ease-gallery-data-el",showDescriptions:!1,showTitles:!1})})})(jQuery);
